/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexoes.ConectaBanco;
import controller.ControllerCliente;
import controller.ControllerProduto;
import controller.ControllerProdutosVendasProdutos;
import controller.ControllerVenda;
import controller.ControllerVendaProduto;
import controller.ControllerVendasCliente;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;
import model.ModelContaVenda;
import model.ModelProduto;
import model.ModelProdutosVendasProdutos;
import model.ModelVenda;
import model.ModelVendaProduto;
import model.ModelVendasCliente;
import util.FormatarData;

/**
 *
 * @author Wesley
 */
public class ViewConsultaVenda extends javax.swing.JInternalFrame {

     /**
     * Estanciando Clientes
     */
    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();

    /**
     * Estanciando Produtos
     */
    ControllerProduto controllerProduto = new ControllerProduto();
    ModelProduto modelProduto = new ModelProduto();
    ArrayList<ModelProduto> listaModelProdutos = new ArrayList<>();

    /**
     * Estanciando lista de vendasCliente
     */
    ArrayList<ModelVendasCliente> listaModelVendasCliente = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();

    /**
     * Estanciando Venda
     */
    ControllerVenda controllerVenda = new ControllerVenda();

    /**
     * Venda
     */
    ArrayList<ModelVenda> listaModelVenda = new ArrayList<>();
    ModelVenda modelVenda = new ModelVenda();
    
    ArrayList<ModelContaVenda> listaModelContaVenda = new ArrayList<>();

    /**
     * Formatação de data
     */
    FormatarData formatarData = new FormatarData();

    /**
     * Vendas Produtos
     */
    ControllerVendaProduto controllerVendaProduto = new ControllerVendaProduto();
    ModelVendaProduto modelVendaProduto = new ModelVendaProduto();
    ArrayList<ModelVendaProduto> listaModelVendaProdutos = new ArrayList<>();

    /**
     * ProdutosVendas Produtos
     */
    ControllerProdutosVendasProdutos controllerProdutosVendasProdutos = new ControllerProdutosVendasProdutos();
    ModelProdutosVendasProdutos modelProdutosVendasProdutos = new ModelProdutosVendasProdutos();
    ArrayList<ModelProdutosVendasProdutos> listaModelProdutosVendasProdutos = new ArrayList<>();

    /**
     * Variavel botão Salvar ou Alterar
     */
    String salvarAlterar;

    DefaultTableModel tmVendas = new DefaultTableModel(null, new String[]{"N.° Venda", "N.°Mesa", "Cliente", "Forma Pagamento", "Observação", "R$ Valor Pago"});
    ListSelectionModel lmsVendas;

    ConectaBanco conectaBanco = new ConectaBanco();
    
    /**
     * Creates new form ViewConsultaVenda
     */
    public ViewConsultaVenda() {
        initComponents();
        dataSistema2();
        retornaPorData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfDataInicio = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jtfDataFim = new javax.swing.JFormattedTextField();
        btPesquisa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtableVendas = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jtfValorTotal2 = new javax.swing.JFormattedTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Conta de Vendas por Data");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas por período", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Data Inicio / Fim");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("De:");

        try {
            jtfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Até:");

        try {
            jtfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btPesquisa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32px/pesquisar.png"))); // NOI18N
        btPesquisa.setText("Pequisar");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        jtableVendas.setModel(tmVendas);
        jtableVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lmsVendas = jtableVendas.getSelectionModel();
        lmsVendas.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    tblPedidoLinhaSelecionada(jtableVendas);

                }
            }
        });
        jtableVendas.setModel(tmVendas);
        jScrollPane3.setViewportView(jtableVendas);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor total R$", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 102, 51))); // NOI18N

        jtfValorTotal2.setBackground(new java.awt.Color(204, 255, 204));
        jtfValorTotal2.setForeground(new java.awt.Color(0, 51, 51));
        jtfValorTotal2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfValorTotal2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtfValorTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorTotal2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfValorTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfValorTotal2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPesquisa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisa)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jtfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Consulta de Vendas");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tblPedidoLinhaSelecionada(JTable tbl) {

        if (tbl.getSelectedRow() != -1) {
            int linha = jtableVendas.getSelectedRow();
            int codigoVenda = (int) jtableVendas.getValueAt(linha, 0);
            listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.retornaListaProdutosVendasProdutosController(codigoVenda);
            //DefaultTableModel modelo = (DefaultTableModel) jtableProdutoVenda.getModel();
            //modelo.setNumRows(0);

            listaModelVenda = controllerVenda.retornaListaVendasPorCodigoController(codigoVenda);
            //modelo.setNumRows(0);

            for (int i = 0; i < listaModelVenda.size(); i++) {
                //jtfComanda.setText(String.valueOf(listaModelVenda.get(i).getVen_comanda()));
                //jtfValorPorVenda.setText(String.valueOf(listaModelVenda.get(i).getVen_valor_liquido()));

            }

        }
    }
    
    /**
     * Carrega as vendas cadastradas
     */
    private void carregarVendas() {
        try {
           
            DefaultTableModel modelo = (DefaultTableModel) jtableVendas.getModel();
            listaModelVendasCliente = controllerVendasCliente.retornaListaVendasCliente();
            listaModelVenda = controllerVenda.retornartListaVendaController();

            //listaModelVenda = controllerVenda.retornartListaVendaPorDataController(dataInicio, dataFim);

            modelo.setNumRows(0);
            int cont = listaModelVenda.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaModelVenda.get(i).getVen_cod(),
                    listaModelVenda.get(i).getVen_comanda()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }    

    public void retornaValorTotalLiquido() {

        try {

            conectaBanco.conexao();
            conectaBanco.executaSQL("SELECT SUM(V.ven_valor_liquido)VALOR_TOTAL\n"
                    + "FROM tblvenda V \n"
                    + "WHERE V.ven_status = 'venda';");

            while (conectaBanco.rs.next()) {
                Double valor = conectaBanco.rs.getDouble("VALOR_TOTAL");
                jtfValorTotal2.setText(String.valueOf(valor));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }

    public void retornaValorTotalLiquidoComData() {

        try {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicio = new java.sql.Date(formato.parse(jtfDataInicio.getText().trim()).getTime());
            Date dataFim = new java.sql.Date(formato.parse(jtfDataFim.getText().trim()).getTime());

            conectaBanco.conexao();
            conectaBanco.executaSQL("SELECT SUM(V.ven_valor_liquido)VALOR_TOTAL\n"
                    + "FROM tblvenda V \n"
                    + "WHERE V.ven_status = 'venda'"
                    + "and V.ven_data BETWEEN '" + dataInicio + "' AND '" + dataFim + "';");

            while (conectaBanco.rs.next()) {
                Double valor = conectaBanco.rs.getDouble("VALOR_TOTAL");
                jtfValorTotal2.setText(String.valueOf(valor));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }
    
    public void retornaPorData() {      
       
        try {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicio = new java.sql.Date(formato.parse(jtfDataInicio.getText().trim()).getTime());
            Date dataFim = new java.sql.Date(formato.parse(jtfDataFim.getText().trim()).getTime());
            
            DefaultTableModel modelo = (DefaultTableModel) jtableVendas.getModel();
            listaModelVendasCliente = controllerVendasCliente.retornaListaVendasCliente();
            //listaModelVenda = controllerVenda.retornartListaVendaController();

            //listaModelVenda = controllerVenda.retornartListaVendaPorDataController(dataInicio, dataFim);
            
            listaModelContaVenda = controllerVenda.retornartListaVendaPorDataFormaPagamentoController(dataInicio, dataFim);
            
            modelo.setNumRows(0);
            int cont = listaModelContaVenda.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaModelContaVenda.get(i).getVen_cod(),
                    listaModelContaVenda.get(i).getVen_comanda(),
                    listaModelContaVenda.get(i).getVen_nome_cliente(),
                    listaModelContaVenda.get(i).getVfp_desc_formapagamento(),
                    listaModelContaVenda.get(i).getVfp_observacao(),
                    listaModelContaVenda.get(i).getVfp_valor_pagamento()
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }

    public void dataSistema() {
        //Tratando a Validação
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date d = new java.util.Date();
        java.sql.Date dataSistema = java.sql.Date.valueOf(formato.format(d));

        jtfDataInicio.setText(dataSistema.toString());
        jtfDataFim.setText(dataSistema.toString());
    }

    public void dataSistema2() {
        long date = System.currentTimeMillis();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dateString = sdf.format(date);

        jtfDataInicio.setText(dateString);
        jtfDataFim.setText(dateString);

        retornaValorTotalLiquidoComData();

    }
    
    
    
    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        retornaValorTotalLiquidoComData();
        retornaPorData();
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void jtfValorTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfValorTotal2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisa;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtableVendas;
    private javax.swing.JFormattedTextField jtfDataFim;
    private javax.swing.JFormattedTextField jtfDataInicio;
    private javax.swing.JFormattedTextField jtfValorTotal2;
    // End of variables declaration//GEN-END:variables
}
