/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexoes.ConectaBanco;
import controller.ControllerCreditoDebito;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.ModelCreditoDebito;
import util.FormatarData;

/**
 *
 * @author Wesley
 */
public class ViewCreditoDebito extends javax.swing.JInternalFrame {

    ArrayList<ModelCreditoDebito> listaModelCreditoDebito = new ArrayList<>();
    ControllerCreditoDebito controllerCreditoDebito = new ControllerCreditoDebito();
    ModelCreditoDebito modelCreditoDebito = new ModelCreditoDebito();
    String salvarAlterar;
    FormatarData formatarData = new FormatarData();

    DefaultTableModel tmCreditoDebito = new DefaultTableModel(null, new String[]{"Id", "Descrição", "Tipo", "Valor R$"});
    ListSelectionModel lmsCreditoDebito;

    ConectaBanco conectaBanco = new ConectaBanco();

    /**
     * Creates new form ViewCreditoDebito
     */
    public ViewCreditoDebito() {
        initComponents();

        dataSistema();
        //carregarCreditoDebitos();
        habilitarDesabilitarCampo(false);
        this.retornaPorData();
        this.retornaValorTotalCreditoComData();
        this.retornaValorTotalDebitoComData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JFormattedTextField();
        jtfValor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jcbFormaPaga = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCreditoDebito = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jtfCredito = new javax.swing.JFormattedTextField();
        jPanel13 = new javax.swing.JPanel();
        jtfDebito = new javax.swing.JFormattedTextField();
        jtfDataInicio = new javax.swing.JFormattedTextField();
        jtfDataFim = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btAlterar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gerenciamento Crédito e Débito");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Crédito / Débito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), java.awt.SystemColor.textHighlight)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Descrição: ");

        jtfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Valor R$:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tipo Crédito / Débito:");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Crédito", "Débito" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Forma de pagamento:");

        jcbFormaPaga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Dinheiro", "Cartão", "Cheque" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("De:");

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32px/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tblCreditoDebito.setModel(tmCreditoDebito);
        jScrollPane1.setViewportView(tblCreditoDebito);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crédito", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jtfCredito.setForeground(new java.awt.Color(0, 0, 102));
        jtfCredito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCredito.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Débito", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jtfDebito.setForeground(new java.awt.Color(0, 0, 102));
        jtfDebito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDebito.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDebitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jtfDebito, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            jtfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Até:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDescricao)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbFormaPaga, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jtfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btPesquisar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btPesquisar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbFormaPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32px/editar.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32px/cancelar2.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32px/lixeira.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32px/novo.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32px/salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar)
                    .addComponent(btCancelar)
                    .addComponent(btSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void carregarCreditoDebitos() {
        listaModelCreditoDebito = controllerCreditoDebito.retornaListaCreditoDebitoController();
        DefaultTableModel modelo = (DefaultTableModel) tblCreditoDebito.getModel();
        modelo.setNumRows(0);

        int cont = listaModelCreditoDebito.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelCreditoDebito.get(i).getCre_cod(),
                listaModelCreditoDebito.get(i).getCre_descricao(),
                listaModelCreditoDebito.get(i).getCre_tipo(),
                listaModelCreditoDebito.get(i).getCre_valor(),});

        }
        this.retornaValoCredito();
        this.retornaValoDebito();
    }

    private void habilitarDesabilitarCampo(boolean condicao) {
        jtfDescricao.setEnabled(condicao);
        jtfValor.setEnabled(condicao);
        jcbFormaPaga.setEnabled(condicao);
        jcbTipo.setEnabled(condicao);
        btSalvar.setEnabled(condicao);

    }

    public void limparCampos() {
        jtfDescricao.setText("");
        jtfValor.setText("");
        jcbFormaPaga.setSelectedItem("Selecione...");
        jcbTipo.setSelectedItem("Selecione...");
    }

    public void salvarCreditoDebito() {
        try {
            modelCreditoDebito.setCre_descricao(this.jtfDescricao.getText().trim().toUpperCase());
            modelCreditoDebito.setCre_data(formatarData.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            modelCreditoDebito.setCre_forma_paga(this.jcbFormaPaga.getSelectedItem().toString());
            modelCreditoDebito.setCre_tipo(this.jcbTipo.getSelectedItem().toString());
            modelCreditoDebito.setCre_valor(Double.parseDouble(this.jtfValor.getText().replace(",", ".")));

            if (jcbFormaPaga.getSelectedItem().equals("Selecione...")) {
                JOptionPane.showMessageDialog(this, "Selecione uma forma de pagamento", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

            } else if (jcbTipo.getSelectedItem().equals("Selecione...")) {
                JOptionPane.showMessageDialog(this, "Selecione Crédito ou Débito", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

            } else if (controllerCreditoDebito.salvarCreditoDebitoController(modelCreditoDebito) > 0) {
                JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                habilitarDesabilitarCampo(false);
                this.retornaPorData();
                this.retornaValorTotalCreditoComData();
                this.retornaValorTotalDebitoComData();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {

            e.printStackTrace();
            System.out.println("Erro no botão salvar");
        }

    }

    public void alterarCreditoDebito() {
        modelCreditoDebito.setCre_descricao(this.jtfDescricao.getText().trim().toUpperCase());
        modelCreditoDebito.setCre_forma_paga(this.jcbFormaPaga.getSelectedItem().toString());
        modelCreditoDebito.setCre_tipo(this.jcbTipo.getSelectedItem().toString());
        modelCreditoDebito.setCre_valor(Double.parseDouble(this.jtfValor.getText().replace(",", ".")));

        if (controllerCreditoDebito.alterarCreditoDebitoController(modelCreditoDebito)) {
            carregarCreditoDebitos();
            JOptionPane.showMessageDialog(this, "Alterado com sucesso!", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
            habilitarDesabilitarCampo(false);
            this.retornaPorData();
            this.retornaValorTotalCreditoComData();
            this.retornaValorTotalDebitoComData();

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void retornaValoCredito() {

        try {

            conectaBanco.conexao();
            conectaBanco.executaSQL("select \n"
                    + "sum(c.cre_valor)ValorCredito\n"
                    + " from tblcreditodebito c\n"
                    + "where c.cre_tipo = 'Crédito';");

            while (conectaBanco.rs.next()) {
                Double valorCredito = conectaBanco.rs.getDouble("ValorCredito");
                jtfCredito.setText(String.valueOf(valorCredito));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }

    public void retornaValoDebito() {

        try {

            conectaBanco.conexao();
            conectaBanco.executaSQL("select \n"
                    + "sum(c.cre_valor)ValorDebito\n"
                    + " from tblcreditodebito c\n"
                    + "where c.cre_tipo = 'Débito';");

            while (conectaBanco.rs.next()) {
                Double valorDebito = conectaBanco.rs.getDouble("ValorDebito");
                jtfDebito.setText(String.valueOf(valorDebito));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }

    public void dataSistema() {
        long date = System.currentTimeMillis();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dateString = sdf.format(date);

        jtfDataInicio.setText(dateString);
        jtfDataFim.setText(dateString);

    }

    public void retornaPorData() {

        try {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicio = new java.sql.Date(formato.parse(jtfDataInicio.getText().trim()).getTime());
            Date dataFim = new java.sql.Date(formato.parse(jtfDataFim.getText().trim()).getTime());

            DefaultTableModel modelo = (DefaultTableModel) tblCreditoDebito.getModel();
            listaModelCreditoDebito = controllerCreditoDebito.retornartListaCredDebPorDataController(dataInicio, dataFim);

            modelo.setNumRows(0);
            int cont = listaModelCreditoDebito.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaModelCreditoDebito.get(i).getCre_cod(),
                    listaModelCreditoDebito.get(i).getCre_descricao(),
                    listaModelCreditoDebito.get(i).getCre_tipo(),
                    listaModelCreditoDebito.get(i).getCre_valor(),});
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }

    public void retornaValorTotalDebitoComData() {

        try {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicio = new java.sql.Date(formato.parse(jtfDataInicio.getText().trim()).getTime());
            Date dataFim = new java.sql.Date(formato.parse(jtfDataFim.getText().trim()).getTime());

            conectaBanco.conexao();
            conectaBanco.executaSQL("select \n"
                    + "sum(c.cre_valor)ValorDebito\n"
                    + " from tblcreditodebito c\n"
                    + "where c.cre_tipo = 'Débito' "
                    + "and c.cre_data BETWEEN '" + dataInicio + "' AND '" + dataFim + "';");

            while (conectaBanco.rs.next()) {
                Double valor = conectaBanco.rs.getDouble("ValorDebito");
                jtfDebito.setText(String.valueOf(valor));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }

    public void retornaValorTotalCreditoComData() {

        try {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicio = new java.sql.Date(formato.parse(jtfDataInicio.getText().trim()).getTime());
            Date dataFim = new java.sql.Date(formato.parse(jtfDataFim.getText().trim()).getTime());

            conectaBanco.conexao();
            conectaBanco.executaSQL("select \n"
                    + "sum(c.cre_valor)ValorCredito\n"
                    + " from tblcreditodebito c\n"
                    + "where c.cre_tipo = 'Crédito' "
                    + "and c.cre_data BETWEEN '" + dataInicio + "' AND '" + dataFim + "';");

            while (conectaBanco.rs.next()) {
                Double valor = conectaBanco.rs.getDouble("ValorCredito");
                jtfCredito.setText(String.valueOf(valor));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }


    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        retornaValorTotalDebitoComData();
        retornaValorTotalCreditoComData();
        retornaPorData();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        salvarAlterar = "alterar";
        int linha = tblCreditoDebito.getSelectedRow();
        btExcluir.setEnabled(false);
        btNovo.setEnabled(false);

        try {
            int codigoCreditoDebito = (int) this.tblCreditoDebito.getValueAt(linha, 0);
            //recuperar dados do banco
            modelCreditoDebito = controllerCreditoDebito.retornaCreditoDebitoController(codigoCreditoDebito);
            //setar na interface 
            this.jtfDescricao.setText(modelCreditoDebito.getCre_descricao());
            this.jtfValor.setText(String.valueOf(modelCreditoDebito.getCre_valor()));
            this.jcbFormaPaga.setSelectedItem(modelCreditoDebito.getCre_forma_paga());
            this.jcbTipo.setSelectedItem(modelCreditoDebito.getCre_tipo());
            habilitarDesabilitarCampo(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        habilitarDesabilitarCampo(false);
        limparCampos();
        btNovo.setEnabled(true);
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            int linha = tblCreditoDebito.getSelectedRow();
            int codigoCreditoDebito = (int) tblCreditoDebito.getValueAt(linha, 0);
            String descricao = (String) tblCreditoDebito.getValueAt(linha, 1);

            int resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir " + descricao + " ?", "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {

                if (controllerCreditoDebito.excluirCreditoDebitoController(codigoCreditoDebito)) {
                    //JOptionPane.showMessageDialog(this, "Produto excluido com sucesso!");
                    this.retornaPorData();
                    this.retornaValorTotalCreditoComData();
                    this.retornaValorTotalDebitoComData();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        habilitarDesabilitarCampo(true);
        jtfDescricao.requestFocus();
        salvarAlterar = "salvar";


    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (salvarAlterar.equals("salvar")) {
            this.salvarCreditoDebito();
        } else if (salvarAlterar.equals("alterar")) {
            this.alterarCreditoDebito();
            btNovo.setEnabled(true);
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void jtfCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCreditoActionPerformed

    private void jtfDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDebitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDebitoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbFormaPaga;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JFormattedTextField jtfCredito;
    private javax.swing.JFormattedTextField jtfDataFim;
    private javax.swing.JFormattedTextField jtfDataInicio;
    private javax.swing.JFormattedTextField jtfDebito;
    private javax.swing.JFormattedTextField jtfDescricao;
    private javax.swing.JFormattedTextField jtfValor;
    private javax.swing.JTable tblCreditoDebito;
    // End of variables declaration//GEN-END:variables
}
