/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexoes.ConectaBanco;
import controller.ControllerCreditoDebito;
import controller.ControllerDespesa;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.ModelCreditoDebito;
import model.ModelDespesa;

/**
 *
 * @author wesleym1
 */
public class ViewFechamento extends javax.swing.JInternalFrame {
    
     ConectaBanco conectaBanco = new ConectaBanco();
     
    ArrayList<ModelCreditoDebito> listaModelCreditoDebito = new ArrayList<>();
    ControllerCreditoDebito controllerCreditoDebito = new ControllerCreditoDebito();
    ModelCreditoDebito modelCreditoDebito = new ModelCreditoDebito();

    ArrayList<ModelDespesa> listarDespesa = new ArrayList<>();
    ControllerDespesa controllerDespesa = new ControllerDespesa();
    ModelDespesa modelDespesa = new ModelDespesa();
    
    DefaultTableModel tmCreditoDebito = new DefaultTableModel(null, new String[]{"Id", "Tipo Despesa", "Descricação", "Valor R$"});
    ListSelectionModel lmsCreditoDebito;

    /**
     * Creates new form ViewFechamento
     */
    public ViewFechamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtfDataInicio = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfDataFim = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        ResultadoCredito = new javax.swing.JLabel();
        ResultadoDebito = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCreditoDebito = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Fechamento");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fechamento Crédito / Débito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), java.awt.SystemColor.textHighlight)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Data de Inicio:");

        try {
            jtfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Até:");

        try {
            jtfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));

        ResultadoCredito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ResultadoCredito.setForeground(new java.awt.Color(0, 102, 102));
        ResultadoCredito.setText("Crédito R$ 0,00");

        ResultadoDebito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ResultadoDebito.setForeground(new java.awt.Color(204, 0, 0));
        ResultadoDebito.setText("Débito R$ 0,00");

        jLabel1.setText("----------------------------------------------------------");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResultadoDebito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResultadoCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultadoCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResultadoDebito)
                .addGap(21, 21, 21))
        );

        tblCreditoDebito.setModel(tmCreditoDebito);
        jScrollPane1.setViewportView(tblCreditoDebito);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Selecione Crédito / Débito:");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Crédito", "Débito" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jtfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jtfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon32px/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPesquisar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void retornaValorCredito() throws ParseException {

        
        String tipoDespesa = String.valueOf(modelDespesa.getDis_cod());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date dataInicio = new java.sql.Date(formato.parse(jtfDataInicio.getText().trim()).getTime());
        Date dataFim = new java.sql.Date(formato.parse(jtfDataFim.getText().trim()).getTime());
               
        try {
            conectaBanco.conexao();
            conectaBanco.executaSQL("select \n"
                    + "sum(c.cre_valor)ValorCredito\n"  
                    + "from tblcreditodebito c\n"
                    + "where c.cre_data BETWEEN '"+dataInicio+"' and '"+dataFim+"'"
                            + "and c.cre_tipo = 'Crédito';");

            while (conectaBanco.rs.next()) {
                Double valorCredito = conectaBanco.rs.getDouble("ValorCredito");
                ResultadoCredito.setText("Valor Total do Crédito R$ "+valorCredito);
                
            }
            

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }
    
    public void retornaValorDebito() throws ParseException {

        
        String tipoDespesa = String.valueOf(modelDespesa.getDis_cod());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date dataInicio = new java.sql.Date(formato.parse(jtfDataInicio.getText().trim()).getTime());
        Date dataFim = new java.sql.Date(formato.parse(jtfDataFim.getText().trim()).getTime());
        
       
        try {
            conectaBanco.conexao();
            conectaBanco.executaSQL("select \n"
                    + "sum(c.cre_valor)ValorDebito\n"  
                    + "from tblcreditodebito c\n"
                    + "where c.cre_data BETWEEN '"+dataInicio+"' and '"+dataFim+"'"
                            + "and c.cre_tipo = 'Débito';");

            while (conectaBanco.rs.next()) {
                Double valorDebito = conectaBanco.rs.getDouble("ValorDebito");
                ResultadoDebito.setText("Valor Total do Débito R$ "+valorDebito);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }
    
    public void retornaPorDataValor() {

        try {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataInicio = new java.sql.Date(formato.parse(jtfDataInicio.getText().trim()).getTime());
            Date dataFim = new java.sql.Date(formato.parse(jtfDataFim.getText().trim()).getTime());

            String tipo = jcbTipo.getSelectedItem().toString();
            
            DefaultTableModel modelo = (DefaultTableModel) tblCreditoDebito.getModel();
            listaModelCreditoDebito = controllerCreditoDebito.retornartListaCredDebPorDataFechamentoController(dataInicio, dataFim, tipo);
            modelo.setNumRows(0);

            int cont = listaModelCreditoDebito.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaModelCreditoDebito.get(i).getCre_cod(),
                    listaModelCreditoDebito.get(i).getCre_tipo_despesa(),
                    listaModelCreditoDebito.get(i).getCre_descricao(),
                    listaModelCreditoDebito.get(i).getCre_valor(),});

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        conectaBanco.conexao();

    }
    
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        retornaPorDataValor();
         try {
             if(jcbTipo.getSelectedItem().equals("Crédito")){
                 retornaValorCredito();
                 ResultadoDebito.setText("Débito R$ 0,00");
             }else if(jcbTipo.getSelectedItem().equals("Débito")){
                 retornaValorDebito();
                 ResultadoCredito.setText("Crédito R$ 0,00");
             }
             
             
         } catch (ParseException ex) {
             Logger.getLogger(ViewFechamento.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ResultadoCredito;
    private javax.swing.JLabel ResultadoDebito;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JFormattedTextField jtfDataFim;
    private javax.swing.JFormattedTextField jtfDataInicio;
    private javax.swing.JTable tblCreditoDebito;
    // End of variables declaration//GEN-END:variables
}
